import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

/// ════════════════════════════════════════════════════════════════════════════
/// SYSTÈME DE LOCALISATION COMPLET - HOSPITAL MANAGEMENT SYSTEM
/// ════════════════════════════════════════════════════════════════════════════
/// 
/// Ce fichier gère TOUTES les traductions de l'application.
/// Langues supportées: Français, English, العربية (avec RTL)
/// ════════════════════════════════════════════════════════════════════════════

// Provider pour la langue - GLOBAL
final languageProvider = StateNotifierProvider<LanguageNotifier, String>((ref) {
  return LanguageNotifier();
});

class LanguageNotifier extends StateNotifier<String> {
  LanguageNotifier() : super('Français');

  void setLanguage(String language) {
    state = language;
  }
  
  /// Vérifie si la langue actuelle est RTL (arabe)
  bool get isRTL => state == 'العربية';
  
  /// Retourne le code de locale
  String get localeCode {
    switch (state) {
      case 'English':
        return 'en';
      case 'العربية':
        return 'ar';
      default:
        return 'fr';
    }
  }
}

// Classe de traductions COMPLÈTES
class AppLocalizations {
  static String get(String key, String language) {
    return _translations[language]?[key] ?? _translations['Français']?[key] ?? key;
  }

  static final Map<String, Map<String, String>> _translations = {
    // ==================== FRANÇAIS ====================
    'Français': {
      // Application / Header
      'hospital_name': 'Hôpital Central',
      'admin_panel': 'Gestion',
      
      // Login
      'login': 'Connexion',
      'welcome_back': 'Bienvenue',
      'email': 'Email',
      'password': 'Mot de passe',
      'login_button': 'Se connecter',
      'please_enter_email': 'Veuillez entrer votre email',
      'please_enter_password': 'Veuillez entrer votre mot de passe',
      'invalid_credentials': 'Identifiants incorrects',
      
      // Navigation
      'dashboard': 'Tableau de bord',
      'patients': 'Patients',
      'appointments': 'Rendez-vous',
      'services': 'Services',
      'care': 'Soins',
      'finance': 'Finances',
      'reports': 'Rapports',
      'notifications': 'Notifications',
      'settings': 'Paramètres',
      'logout': 'Déconnexion',
      
      // Dashboard
      'good_morning': 'Bonjour',
      'good_afternoon': 'Bon après-midi',
      'good_evening': 'Bonsoir',
      'total_patients': 'Total Patients',
      'appointments_today': 'RDV Aujourd\'hui',
      'available_beds': 'Lits Disponibles',
      'monthly_revenue': 'Revenus du Mois',
      'recent_activity': 'Activité Récente',
      'quick_stats': 'Statistiques Rapides',
      'budget_by_service': 'Budget par Service',
      'recent_care': 'Soins Récents',
      'quick_actions': 'Actions Rapides',
      'new_patient': 'Nouveau Patient',
      'budget': 'Budget',
      'current_cost': 'Coût actuel',
      'no_service': 'Aucun service',
      'no_recent_care': 'Aucun soin récent',
      'active': 'Actif',
      'inactive': 'Inactif',
      
      // Patients
      'patient_list': 'Liste des Patients',
      'add_patient': 'Ajouter Patient',
      'edit_patient': 'Modifier Patient',
      'delete_patient': 'Supprimer Patient',
      'search_patient': 'Rechercher un patient...',
      'name': 'Nom',
      'first_name': 'Prénom',
      'birth_date': 'Date de Naissance',
      'phone': 'Téléphone',
      'address': 'Adresse',
      'gender': 'Genre',
      'male': 'Homme',
      'female': 'Femme',
      'blood_type': 'Groupe Sanguin',
      'social_security': 'N° Sécurité Sociale',
      'no_patient_found': 'Aucun patient trouvé',
      'patient_added': 'Patient ajouté avec succès',
      'patient_updated': 'Patient modifié avec succès',
      'patient_deleted': 'Patient supprimé avec succès',
      'patient_details': 'Détails Patient',
      'select_date': 'Sélectionner une date',
      'total_cost': 'Coût total',
      'care_count': 'Nombre de soins',
      
      // Services
      'service_list': 'Liste des Services',
      'add_service': 'Ajouter Service',
      'edit_service': 'Modifier Service',
      'delete_service': 'Supprimer Service',
      'search_service': 'Rechercher un service...',
      'service_name': 'Nom du Service',
      'description': 'Description',
      'monthly_budget': 'Budget Mensuel',
      'annual_budget': 'Budget Annuel',
      'no_service_found': 'Aucun service trouvé',
      'service_added': 'Service ajouté avec succès',
      'service_updated': 'Service modifié avec succès',
      'service_deleted': 'Service supprimé avec succès',
      
      // Soins
      'care_list': 'Liste des Soins',
      'add_care': 'Ajouter Soin',
      'edit_care': 'Modifier Soin',
      'delete_care': 'Supprimer Soin',
      'search_care': 'Rechercher un soin...',
      'care_type': 'Type de Soin',
      'care_date': 'Date du Soin',
      'care_cost': 'Coût du Soin',
      'notes': 'Notes',
      'select_patient': 'Sélectionner un patient',
      'select_service': 'Sélectionner un service',
      'no_care_found': 'Aucun soin trouvé',
      'care_added': 'Soin ajouté avec succès',
      'care_updated': 'Soin modifié avec succès',
      'care_deleted': 'Soin supprimé avec succès',
      
      // Rendez-vous
      'appointment_list': 'Liste des Rendez-vous',
      'add_appointment': 'Nouveau Rendez-vous',
      'edit_appointment': 'Modifier Rendez-vous',
      'delete_appointment': 'Supprimer Rendez-vous',
      'search_appointment': 'Rechercher un rendez-vous...',
      'date': 'Date',
      'time': 'Heure',
      'doctor': 'Médecin',
      'reason': 'Motif',
      'status': 'Statut',
      'pending': 'En attente',
      'confirmed': 'Confirmé',
      'cancelled': 'Annulé',
      'completed': 'Terminé',
      'no_appointment_found': 'Aucun rendez-vous trouvé',
      
      // Finance
      'finance_overview': 'Gestion financière de l\'établissement',
      'total_revenue': 'Revenus Totaux',
      'total_expenses': 'Dépenses Totales',
      'net_profit': 'Bénéfice Net',
      'pending_invoices': 'Factures en attente',
      'export': 'Exporter',
      'export_pdf': 'Export PDF',
      'export_excel': 'Export Excel',
      'export_csv': 'Export CSV',
      'revenue_vs_expenses': 'Revenus vs Dépenses',
      'recent_transactions': 'Transactions Récentes',
      'overview': 'Vue d\'ensemble',
      'revenue': 'Revenus',
      'expenses': 'Dépenses',
      'week': 'Semaine',
      'month': 'Mois',
      'year': 'Année',
      'export_success': 'Export téléchargé avec succès',
      'export_error': 'Erreur lors de l\'export',
      'revenue_sources': 'Sources de revenus',
      'top_services': 'Top Services',
      'consultations': 'Consultations',
      'surgeries': 'Chirurgies',
      'analyses': 'Analyses',
      'other': 'Autres',
      'revenue_details': 'Détail des revenus',
      'date': 'Date',
      'description': 'Description',
      'service': 'Service',
      'amount': 'Montant',
      'category': 'Catégorie',
      'expenses_by_category': 'Dépenses par catégorie',
      'expenses_trend': 'Tendance des dépenses',
      'recent_expenses': 'Dépenses récentes',
      'salaries': 'Salaires',
      'supplies': 'Fournitures',
      'maintenance': 'Maintenance',
      'energy': 'Énergie',
      'total_budget': 'Budget Total',
      'used': 'Utilisé',
      'remaining': 'Restant',
      'usage_rate': 'Taux utilisation',
      'budget_by_service': 'Budget par service',
      'export_finances': 'Exporter les finances',
      'complete_report_with_charts': 'Rapport complet avec graphiques',
      'detailed_data_table': 'Données détaillées en tableau',
      'compatible_format': 'Format compatible avec tous les outils',
      'cancel': 'Annuler',
      'export_downloaded_success': 'Export {format} téléchargé avec succès!',
      'export_error_format': 'Erreur lors de l\'export {format}',
      'december_salaries': 'Salaires Décembre',
      'medical_consumables': 'Consommables médicaux',
      'scanner_repair': 'Réparation scanner',
      'electricity_bill': 'Facture électricité',
      'cardiology_consultation': 'Consultation cardiologie',
      'medical_supplies': 'Fournitures médicales',
      'lab_analysis': 'Analyse laboratoire',
      'equipment_maintenance': 'Maintenance équipements',
      'outpatient_surgery': 'Chirurgie ambulatoire',
      'month_jan': 'Jan',
      'month_feb': 'Fév',
      'month_mar': 'Mar',
      'month_apr': 'Avr',
      'month_may': 'Mai',
      'month_jun': 'Jun',
      
      // Rapports
      'reports_title': 'Analyses et statistiques de l\'hôpital',
      'generate_report': 'Générer Rapport',
      'monthly_report': 'Rapport Mensuel',
      'download': 'Télécharger',
      'view': 'Visualiser',
      'print': 'Imprimer',
      'print_report': 'Imprimer le rapport',
      'print_directly': 'Imprimer le rapport directement',
      'report_type': 'Type de Rapport',
      'all': 'Tous',
      'monthly_evolution': 'Évolution mensuelle',
      'distribution_by_service': 'Répartition par service',
      'recent_reports': 'Rapports récents',
      'see_all': 'Voir tout',
      'export_reports': 'Exporter les rapports',
      'patients_treated': 'Patients traités',
      'revenue_label': 'Revenus',
      'consultations_label': 'Consultations',
      'occupation_rate': 'Taux occupation',
      'patients_chart': 'Patients',
      'revenue_chart': 'Revenus (k€)',
      'cardiology': 'Cardiologie',
      'pediatrics': 'Pédiatrie',
      'emergency': 'Urgences',
      'monthly_report_june': 'Rapport mensuel - Juin 2024',
      'financial_analysis_q2': 'Analyse financière Q2',
      'patient_statistics': 'Statistiques patients',
      'service_performance': 'Performance services',
      'general': 'Général',
      'finances': 'Finances',
      'report_downloaded': '"{title}" téléchargé!',
      'report_download_error': 'Erreur lors du téléchargement de "{title}"',
      'executive_summary': 'Résumé Exécutif',
      'executive_summary_text': 'Ce rapport présente une analyse complète des activités hospitalières pour la période sélectionnée. Les indicateurs clés montrent une amélioration de 12% des performances globales.',
      'main_statistics': 'Statistiques Principales',
      'main_statistics_text': '• Nombre de patients traités: 1,234\n• Taux d\'occupation: 78%\n• Durée moyenne de séjour: 4.2 jours\n• Taux de satisfaction: 92%',
      'financial_performance': 'Performances Financières',
      'financial_performance_text': '• Revenus totaux: 56,780 €\n• Coûts opérationnels: 42,300 €\n• Marge bénéficiaire: 25.5%\n• Croissance vs période précédente: +8%',
      'recommendations': 'Recommandations',
      'recommendations_text': '1. Optimiser le taux d\'occupation des lits\n2. Réduire les temps d\'attente aux urgences\n3. Améliorer le suivi post-consultation\n4. Investir dans les équipements de diagnostic',
      'close': 'Fermer',
      
      // Notifications
      'notification_list': 'Liste des Notifications',
      'mark_all_read': 'Tout marquer comme lu',
      'no_notifications': 'Aucune notification',
      'today': 'Aujourd\'hui',
      'yesterday': 'Hier',
      'this_week': 'Cette semaine',
      
      // Settings/Paramètres
      'settings_title': 'Configurez votre application',
      'profile': 'Profil',
      'preferences': 'Préférences',
      'account': 'Compte',
      'appearance': 'Apparence',
      'change_password': 'Changer le mot de passe',
      'current_password': 'Mot de passe actuel',
      'new_password': 'Nouveau mot de passe',
      'confirm_password': 'Confirmer le mot de passe',
      'language': 'Langue',
      'choose_language': 'Choisir la langue de l\'application',
      'dark_mode': 'Mode Sombre',
      'enable_dark_theme': 'Activer le thème sombre',
      'notifications_enabled': 'Notifications activées',
      'push_notifications': 'Notifications push',
      'email_notifications': 'Notifications email',
      'sms_notifications': 'Notifications SMS',
      'date_format': 'Format de Date',
      'choose_date_format': 'Choisir le format d\'affichage',
      'security': 'Sécurité',
      'two_factor': 'Authentification à deux facteurs',
      'active_sessions': 'Sessions actives',
      'manage_sessions': 'Gérer vos sessions connectées',
      'data': 'Données',
      'export_data': 'Exporter les données',
      'download_data_copy': 'Télécharger une copie de vos données',
      'backups': 'Sauvegardes',
      'manage_backups': 'Gérer les sauvegardes automatiques',
      'clear_cache': 'Nettoyer le cache',
      'free_storage': 'Libérer de l\'espace de stockage',
      'danger_zone': 'Zone de danger',
      'reset_settings': 'Réinitialiser les paramètres',
      'restore_defaults': 'Restaurer les paramètres par défaut',
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'close': 'Fermer',
      
      // Common/Messages
      'actions': 'Actions',
      'edit': 'Modifier',
      'delete': 'Supprimer',
      'confirm': 'Confirmer',
      'success': 'Succès',
      'error': 'Erreur',
      'loading': 'Chargement...',
      'no_data': 'Aucune donnée',
      'search': 'Rechercher',
      'filter': 'Filtrer',
      'yes': 'Oui',
      'no': 'Non',
      'back': 'Retour',
      'next': 'Suivant',
      'previous': 'Précédent',
      'required_field': 'Ce champ est requis',
      'confirm_delete': 'Êtes-vous sûr de vouloir supprimer?',
      'delete_success': 'Suppression réussie',
      'save_success': 'Enregistrement réussi',
      'password_changed': 'Mot de passe modifié avec succès',
      'password_error': 'Mot de passe actuel incorrect',
      'password_mismatch': 'Les mots de passe ne correspondent pas',
      'password_too_short': 'Le mot de passe doit contenir au moins 6 caractères',
      'passwords_dont_match': 'Les mots de passe ne correspondent pas',
      'language_changed': 'Langue changée avec succès',
      'changes_saved': 'Modifications enregistrées',
      'operation_success': 'Opération réussie',
      'operation_failed': 'Opération échouée',
      
      // Configuration initiale du mot de passe
      'initial_password_setup': 'Configuration initiale du mot de passe',
      'setup_password_description': 'Veuillez définir votre mot de passe pour sécuriser votre compte',
      'password_min_length': 'Minimum 6 caractères',
      'password_setup_success': 'Mot de passe configuré avec succès. Vous pouvez maintenant vous connecter.',
      'password_setup_error': 'Erreur lors de la configuration du mot de passe',
      'setup_password_button': 'Configurer le mot de passe',
      
      // Clés supplémentaires pour les dialogs et formulaires
      'create': 'Créer',
      'modify': 'Modifier',
      'new_service': 'Nouveau service',
      'modify_service': 'Modifier le service',
      'new_care': 'Nouveau soin',
      'modify_care': 'Modifier le soin',
      'new_appointment': 'Nouveau rendez-vous',
      'modify_appointment': 'Modifier le rendez-vous',
      'new_patient_title': 'Nouveau patient',
      'modify_patient': 'Modifier le patient',
      'patient_id': 'ID Patient',
      'cost_euro': 'Coût (€)',
      'budget_euro': 'Budget (€)',
      'budget_used': 'Budget utilisé',
      'remaining': 'Restant',
      'fill_required_fields': 'Veuillez remplir tous les champs requis',
      'confirm_delete_service': 'Voulez-vous vraiment supprimer ce service ?',
      'confirm_delete_care': 'Voulez-vous vraiment supprimer ce soin ?',
      'confirm_delete_appointment': 'Voulez-vous vraiment supprimer ce rendez-vous ?',
      'confirm_delete_patient': 'Voulez-vous vraiment supprimer ce patient ?',
      'retry': 'Réessayer',
      'total_cost': 'Coût total',
      'statistics': 'Statistiques',
      'appointments_for_date': 'Rendez-vous du jour',
      'no_appointments_for_date': 'Aucun rendez-vous pour cette date',
      'status_updated': 'Statut mis à jour',
      'notes_optional': 'Notes (optionnel)',
      'patient_details': 'Détails Patient',
      'no_care_recorded': 'Aucun soin enregistré',
      'select_date': 'Sélectionner une date',
      'please_select_date': 'Veuillez sélectionner une date',
      
      // Types de soins
      'consultation': 'Consultation',
      'surgery': 'Chirurgie',
      'analysis': 'Analyse',
      'radiology': 'Radiologie',
      'emergency': 'Urgence',
      
      // Paramètres additionnels
      'modify_profile': 'Modifier le profil',
      'administrator': 'Administrateur',
      'super_admin': 'Super Admin',
      'enable_2fa': 'Activer 2FA',
      'disable_2fa': 'Désactiver 2FA',
      'scan_qr_code': 'Scannez ce QR code',
      'enter_2fa_code': 'Entrez votre code 2FA',
      'verification_code': 'Code de vérification',
      'invalid_code': 'Code invalide (minimum 6 chiffres)',
      '2fa_enabled': '2FA activé avec succès',
      '2fa_disabled': '2FA désactivé',
      'current': 'Actuel',
      'disconnect_all': 'Déconnecter tout',
      'last_backup': 'Dernière sauvegarde',
      'auto_backup': 'Sauvegarde automatique',
      'backup_now': 'Sauvegarder maintenant',
      'json_export': 'Export JSON',
      'clear_cache_confirm': 'Cela supprimera les fichiers temporaires. Continuer ?',
      'cache_cleared': 'Cache nettoyé avec succès',
      'reset_confirm': 'Êtes-vous sûr de vouloir réinitialiser tous les paramètres ?',
      'logout_confirm': 'Êtes-vous sûr de vouloir vous déconnecter ?',
      'report_complete': 'Rapport complet avec graphiques',
      'detailed_data': 'Données détaillées en tableau',
      'compatible_format': 'Format compatible avec tous les outils',
      'print_directly': 'Imprimer le rapport directement',
      'view_all': 'Voir tout',
      'export_reports': 'Exporter les rapports',
      'export_finances': 'Exporter les finances',
      'income_sources': 'Sources de revenus',
      'top_services': 'Top Services',
      'revenue_details': 'Détail des revenus',
      'expense_categories': 'Dépenses par catégorie',
      'expense_trend': 'Tendance des dépenses',
      'recent_expenses': 'Dépenses récentes',
      'category': 'Catégorie',
      'amount': 'Montant',
      
      // Notifications
      'unread': 'Non lues',
      'info': 'Info',
      'warning': 'Attention',
      'mark_read': 'Marquer lu',
      'mark_unread': 'Marquer non lu',
      'summary': 'Résumé',
      'errors': 'Erreurs',
      'all_read': 'Toutes les notifications marquées comme lues',
      'notification_deleted': 'Notification supprimée',
      
      // Paramètres - Clés additionnelles
      'receive_push_notifications': 'Recevoir les notifications dans l\'app',
      'receive_email_notifications': 'Recevoir les notifications par email',
      'receive_sms_notifications': 'Recevoir les notifications par SMS',
      'push_enabled': 'Notifications push activées',
      'push_disabled': 'Notifications push désactivées',
      'email_enabled': 'Notifications email activées',
      'email_disabled': 'Notifications email désactivées',
      'sms_enabled': 'Notifications SMS activées',
      'sms_disabled': 'Notifications SMS désactivées',
      'modify_current_password': 'Modifier votre mot de passe actuel',
      'logout_from_app': 'Se déconnecter de l\'application',
      'other_sessions_disconnected': 'Autres sessions déconnectées',
      'current_session': 'Session actuelle',
      'today_at': 'Aujourd\'hui à',
      'daily_at': 'Tous les jours à',
      'backup_started': 'Sauvegarde lancée',
      'backup_download': 'Téléchargement de la sauvegarde...',
      'pdf_export_progress': 'Export PDF en cours...',
      'excel_export_progress': 'Export Excel en cours...',
      'json_export_progress': 'Export JSON en cours...',
      'cache_cleared_mb': 'Cache nettoyé avec succès',
      'reset_warning': 'Êtes-vous sûr de vouloir réinitialiser tous les paramètres ?',
      'settings_reset': 'Paramètres réinitialisés',
      'profile_updated': 'Profil mis à jour',
      'total': 'Total',
      'in_progress': 'En cours',
      
      // Main Layout
      'profile_admin': 'Profil Administrateur',
      'member_since': 'Membre depuis',
      'january': 'Janvier',
      'role': 'Rôle',
      'average': 'Moyenne',
      'appointment_added': 'Rendez-vous créé avec succès',
      'appointment_updated': 'Rendez-vous modifié avec succès',
      'appointment_deleted': 'Rendez-vous supprimé avec succès',
      
      // Finances
      'consultations': 'Consultations',
      'surgeries': 'Chirurgies',
      'analyses': 'Analyses',
      'others': 'Autres',
      'salaries': 'Salaires',
      'supplies': 'Fournitures',
      'maintenance': 'Maintenance',
      'energy': 'Énergie',
      'budget_total': 'Budget Total',
      'used': 'Utilisé',
      'usage_rate': 'Taux utilisation',
      'cardiology': 'Cardiologie',
      'pediatrics': 'Pédiatrie',
      'emergencies': 'Urgences',
      'jan': 'Jan',
      'feb': 'Fév',
      'mar': 'Mar',
      'apr': 'Avr',
      'may': 'Mai',
      'jun': 'Jun',
      
      // Reports
      'patients_treated': 'Patients traités',
      'occupation_rate': 'Taux occupation',
      'executive_summary': 'Résumé Exécutif',
      'main_statistics': 'Statistiques Principales',
      
      // Soins types
      'consultation_cardiology': 'Consultation cardiologie',
      'medical_supplies': 'Fournitures médicales',
    },
    
    // ==================== ENGLISH ====================
    'English': {
      // Application / Header
      'hospital_name': 'Central Hospital',
      'admin_panel': 'Management',
      
      // Login
      'login': 'Login',
      'welcome_back': 'Welcome Back',
      'email': 'Email',
      'password': 'Password',
      'login_button': 'Sign In',
      'please_enter_email': 'Please enter your email',
      'please_enter_password': 'Please enter your password',
      'invalid_credentials': 'Invalid credentials',
      
      // Navigation
      'dashboard': 'Dashboard',
      'patients': 'Patients',
      'appointments': 'Appointments',
      'services': 'Services',
      'care': 'Care',
      'finance': 'Finance',
      'reports': 'Reports',
      'notifications': 'Notifications',
      'settings': 'Settings',
      'logout': 'Logout',
      
      // Dashboard
      'good_morning': 'Good morning',
      'good_afternoon': 'Good afternoon',
      'good_evening': 'Good evening',
      'total_patients': 'Total Patients',
      'appointments_today': 'Today\'s Appointments',
      'available_beds': 'Available Beds',
      'monthly_revenue': 'Monthly Revenue',
      'recent_activity': 'Recent Activity',
      'quick_stats': 'Quick Stats',
      'budget_by_service': 'Budget by Service',
      'recent_care': 'Recent Care',
      'quick_actions': 'Quick Actions',
      'new_patient': 'New Patient',
      'budget': 'Budget',
      'current_cost': 'Current Cost',
      'no_service': 'No service',
      'no_recent_care': 'No recent care',
      'active': 'Active',
      'inactive': 'Inactive',
      
      // Patients
      'patient_list': 'Patient List',
      'add_patient': 'Add Patient',
      'edit_patient': 'Edit Patient',
      'delete_patient': 'Delete Patient',
      'search_patient': 'Search patient...',
      'name': 'Name',
      'first_name': 'First Name',
      'birth_date': 'Birth Date',
      'phone': 'Phone',
      'address': 'Address',
      'gender': 'Gender',
      'male': 'Male',
      'female': 'Female',
      'blood_type': 'Blood Type',
      'social_security': 'Social Security Number',
      'no_patient_found': 'No patient found',
      'patient_added': 'Patient added successfully',
      'patient_updated': 'Patient updated successfully',
      'patient_deleted': 'Patient deleted successfully',
      'patient_details': 'Patient Details',
      'select_date': 'Select a date',
      'total_cost': 'Total cost',
      'care_count': 'Number of care',
      
      // Services
      'service_list': 'Service List',
      'add_service': 'Add Service',
      'edit_service': 'Edit Service',
      'delete_service': 'Delete Service',
      'search_service': 'Search service...',
      'service_name': 'Service Name',
      'description': 'Description',
      'monthly_budget': 'Monthly Budget',
      'annual_budget': 'Annual Budget',
      'no_service_found': 'No service found',
      'service_added': 'Service added successfully',
      'service_updated': 'Service updated successfully',
      'service_deleted': 'Service deleted successfully',
      
      // Soins/Care
      'care_list': 'Care List',
      'add_care': 'Add Care',
      'edit_care': 'Edit Care',
      'delete_care': 'Delete Care',
      'search_care': 'Search care...',
      'care_type': 'Care Type',
      'care_date': 'Care Date',
      'care_cost': 'Care Cost',
      'notes': 'Notes',
      'select_patient': 'Select a patient',
      'select_service': 'Select a service',
      'no_care_found': 'No care found',
      'care_added': 'Care added successfully',
      'care_updated': 'Care updated successfully',
      'care_deleted': 'Care deleted successfully',
      
      // Appointments
      'appointment_list': 'Appointment List',
      'add_appointment': 'New Appointment',
      'edit_appointment': 'Edit Appointment',
      'delete_appointment': 'Delete Appointment',
      'search_appointment': 'Search appointment...',
      'date': 'Date',
      'time': 'Time',
      'doctor': 'Doctor',
      'reason': 'Reason',
      'status': 'Status',
      'pending': 'Pending',
      'confirmed': 'Confirmed',
      'cancelled': 'Cancelled',
      'completed': 'Completed',
      'no_appointment_found': 'No appointment found',
      
      // Finance
      'finance_overview': 'Financial Management',
      'total_revenue': 'Total Revenue',
      'total_expenses': 'Total Expenses',
      'net_profit': 'Net Profit',
      'pending_invoices': 'Pending Invoices',
      'export': 'Export',
      'export_pdf': 'Export PDF',
      'export_excel': 'Export Excel',
      'export_csv': 'Export CSV',
      'revenue_vs_expenses': 'Revenue vs Expenses',
      'recent_transactions': 'Recent Transactions',
      'overview': 'Overview',
      'revenue': 'Revenue',
      'expenses': 'Expenses',
      'week': 'Week',
      'month': 'Month',
      'year': 'Year',
      'export_success': 'Export downloaded successfully',
      'export_error': 'Export error',
      'revenue_sources': 'Revenue Sources',
      'top_services': 'Top Services',
      'consultations': 'Consultations',
      'surgeries': 'Surgeries',
      'analyses': 'Analyses',
      'other': 'Other',
      'revenue_details': 'Revenue Details',
      'date': 'Date',
      'description': 'Description',
      'service': 'Service',
      'amount': 'Amount',
      'category': 'Category',
      'expenses_by_category': 'Expenses by Category',
      'expenses_trend': 'Expenses Trend',
      'recent_expenses': 'Recent Expenses',
      'salaries': 'Salaries',
      'supplies': 'Supplies',
      'maintenance': 'Maintenance',
      'energy': 'Energy',
      'total_budget': 'Total Budget',
      'used': 'Used',
      'remaining': 'Remaining',
      'usage_rate': 'Usage Rate',
      'budget_by_service': 'Budget by Service',
      'export_finances': 'Export Finances',
      'complete_report_with_charts': 'Complete report with charts',
      'detailed_data_table': 'Detailed data in table format',
      'compatible_format': 'Format compatible with all tools',
      'cancel': 'Cancel',
      'export_downloaded_success': '{format} export downloaded successfully!',
      'export_error_format': 'Error exporting {format}',
      'december_salaries': 'December Salaries',
      'medical_consumables': 'Medical consumables',
      'scanner_repair': 'Scanner repair',
      'electricity_bill': 'Electricity bill',
      'cardiology_consultation': 'Cardiology consultation',
      'medical_supplies': 'Medical supplies',
      'lab_analysis': 'Lab analysis',
      'equipment_maintenance': 'Equipment maintenance',
      'outpatient_surgery': 'Outpatient surgery',
      'month_jan': 'Jan',
      'month_feb': 'Feb',
      'month_mar': 'Mar',
      'month_apr': 'Apr',
      'month_may': 'May',
      'month_jun': 'Jun',
      
      // Reports
      'reports_title': 'Hospital Statistics and Analysis',
      'generate_report': 'Generate Report',
      'monthly_report': 'Monthly Report',
      'download': 'Download',
      'view': 'View',
      'print': 'Print',
      'print_report': 'Print Report',
      'print_directly': 'Print report directly',
      'report_type': 'Report Type',
      'all': 'All',
      'monthly_evolution': 'Monthly Evolution',
      'distribution_by_service': 'Distribution by Service',
      'recent_reports': 'Recent Reports',
      'see_all': 'See all',
      'export_reports': 'Export Reports',
      'patients_treated': 'Patients treated',
      'revenue_label': 'Revenue',
      'consultations_label': 'Consultations',
      'occupation_rate': 'Occupation rate',
      'patients_chart': 'Patients',
      'revenue_chart': 'Revenue (k€)',
      'cardiology': 'Cardiology',
      'pediatrics': 'Pediatrics',
      'emergency': 'Emergency',
      'monthly_report_june': 'Monthly Report - June 2024',
      'financial_analysis_q2': 'Q2 Financial Analysis',
      'patient_statistics': 'Patient Statistics',
      'service_performance': 'Service Performance',
      'general': 'General',
      'finances': 'Finances',
      'report_downloaded': '"{title}" downloaded!',
      'report_download_error': 'Error downloading "{title}"',
      'executive_summary': 'Executive Summary',
      'executive_summary_text': 'This report presents a comprehensive analysis of hospital activities for the selected period. Key indicators show a 12% improvement in overall performance.',
      'main_statistics': 'Main Statistics',
      'main_statistics_text': '• Patients treated: 1,234\n• Occupancy rate: 78%\n• Average stay duration: 4.2 days\n• Satisfaction rate: 92%',
      'financial_performance': 'Financial Performance',
      'financial_performance_text': '• Total revenue: €56,780\n• Operating costs: €42,300\n• Profit margin: 25.5%\n• Growth vs previous period: +8%',
      'recommendations': 'Recommendations',
      'recommendations_text': '1. Optimize bed occupancy rate\n2. Reduce emergency wait times\n3. Improve post-consultation follow-up\n4. Invest in diagnostic equipment',
      'close': 'Close',
      
      // Notifications
      'notification_list': 'Notification List',
      'mark_all_read': 'Mark all as read',
      'no_notifications': 'No notifications',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'this_week': 'This week',
      
      // Settings
      'settings_title': 'Configure your application',
      'profile': 'Profile',
      'preferences': 'Preferences',
      'account': 'Account',
      'appearance': 'Appearance',
      'change_password': 'Change Password',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'confirm_password': 'Confirm Password',
      'language': 'Language',
      'choose_language': 'Choose application language',
      'dark_mode': 'Dark Mode',
      'enable_dark_theme': 'Enable dark theme',
      'notifications_enabled': 'Notifications enabled',
      'push_notifications': 'Push notifications',
      'email_notifications': 'Email notifications',
      'sms_notifications': 'SMS notifications',
      'date_format': 'Date Format',
      'choose_date_format': 'Choose display format',
      'security': 'Security',
      'two_factor': 'Two-Factor Authentication',
      'active_sessions': 'Active Sessions',
      'manage_sessions': 'Manage your connected sessions',
      'data': 'Data',
      'export_data': 'Export Data',
      'download_data_copy': 'Download a copy of your data',
      'backups': 'Backups',
      'manage_backups': 'Manage automatic backups',
      'clear_cache': 'Clear Cache',
      'free_storage': 'Free up storage space',
      'danger_zone': 'Danger Zone',
      'reset_settings': 'Reset Settings',
      'restore_defaults': 'Restore default settings',
      'save': 'Save',
      'cancel': 'Cancel',
      'close': 'Close',
      
      // Common/Messages
      'actions': 'Actions',
      'edit': 'Edit',
      'delete': 'Delete',
      'confirm': 'Confirm',
      'success': 'Success',
      'error': 'Error',
      'loading': 'Loading...',
      'no_data': 'No data',
      'search': 'Search',
      'filter': 'Filter',
      'yes': 'Yes',
      'no': 'No',
      'back': 'Back',
      'next': 'Next',
      'previous': 'Previous',
      'required_field': 'This field is required',
      'confirm_delete': 'Are you sure you want to delete?',
      'delete_success': 'Successfully deleted',
      'save_success': 'Successfully saved',
      'password_changed': 'Password changed successfully',
      'password_error': 'Incorrect current password',
      'password_mismatch': 'Passwords do not match',
      'password_too_short': 'Password must be at least 6 characters',
      'passwords_dont_match': 'Passwords do not match',
      'language_changed': 'Language changed successfully',
      'changes_saved': 'Changes saved',
      'operation_success': 'Operation successful',
      'operation_failed': 'Operation failed',
      
      // Initial password setup
      'initial_password_setup': 'Initial Password Setup',
      'setup_password_description': 'Please set your password to secure your account',
      'password_min_length': 'Minimum 6 characters',
      'password_setup_success': 'Password set successfully. You can now log in.',
      'password_setup_error': 'Error setting up password',
      'setup_password_button': 'Set Password',
      
      // Additional keys for dialogs and forms
      'create': 'Create',
      'modify': 'Modify',
      'new_service': 'New service',
      'modify_service': 'Modify service',
      'new_care': 'New care',
      'modify_care': 'Modify care',
      'new_appointment': 'New appointment',
      'modify_appointment': 'Modify appointment',
      'new_patient_title': 'New patient',
      'modify_patient': 'Modify patient',
      'patient_id': 'Patient ID',
      'cost_euro': 'Cost (€)',
      'budget_euro': 'Budget (€)',
      'budget_used': 'Budget used',
      'remaining': 'Remaining',
      'fill_required_fields': 'Please fill in all required fields',
      'confirm_delete_service': 'Do you really want to delete this service?',
      'confirm_delete_care': 'Do you really want to delete this care?',
      'confirm_delete_appointment': 'Do you really want to delete this appointment?',
      'confirm_delete_patient': 'Do you really want to delete this patient?',
      'retry': 'Retry',
      'total_cost': 'Total cost',
      'statistics': 'Statistics',
      'appointments_for_date': 'Day appointments',
      'no_appointments_for_date': 'No appointments for this date',
      'status_updated': 'Status updated',
      'notes_optional': 'Notes (optional)',
      'patient_details': 'Patient Details',
      'no_care_recorded': 'No care recorded',
      'select_date': 'Select a date',
      'please_select_date': 'Please select a date',
      
      // Care types
      'consultation': 'Consultation',
      'surgery': 'Surgery',
      'analysis': 'Analysis',
      'radiology': 'Radiology',
      'emergency': 'Emergency',
      
      // Additional settings
      'modify_profile': 'Modify profile',
      'administrator': 'Administrator',
      'super_admin': 'Super Admin',
      'enable_2fa': 'Enable 2FA',
      'disable_2fa': 'Disable 2FA',
      'scan_qr_code': 'Scan this QR code',
      'enter_2fa_code': 'Enter your 2FA code',
      'verification_code': 'Verification code',
      'invalid_code': 'Invalid code (minimum 6 digits)',
      '2fa_enabled': '2FA enabled successfully',
      '2fa_disabled': '2FA disabled',
      'current': 'Current',
      'disconnect_all': 'Disconnect all',
      'last_backup': 'Last backup',
      'auto_backup': 'Automatic backup',
      'backup_now': 'Backup now',
      'json_export': 'JSON Export',
      'clear_cache_confirm': 'This will delete temporary files. Continue?',
      'cache_cleared': 'Cache cleared successfully',
      'reset_confirm': 'Are you sure you want to reset all settings?',
      'logout_confirm': 'Are you sure you want to log out?',
      'report_complete': 'Complete report with charts',
      'detailed_data': 'Detailed data in table',
      'compatible_format': 'Format compatible with all tools',
      'print_directly': 'Print report directly',
      'view_all': 'View all',
      'export_reports': 'Export reports',
      'export_finances': 'Export finances',
      'income_sources': 'Income sources',
      'top_services': 'Top Services',
      'revenue_details': 'Revenue details',
      'expense_categories': 'Expense categories',
      'expense_trend': 'Expense trend',
      'recent_expenses': 'Recent expenses',
      'category': 'Category',
      'amount': 'Amount',
      
      // Notifications
      'unread': 'Unread',
      'info': 'Info',
      'warning': 'Warning',
      'mark_read': 'Mark read',
      'mark_unread': 'Mark unread',
      'summary': 'Summary',
      'errors': 'Errors',
      'all_read': 'All notifications marked as read',
      'notification_deleted': 'Notification deleted',
      
      // Settings - Additional Keys
      'receive_push_notifications': 'Receive notifications in the app',
      'receive_email_notifications': 'Receive notifications by email',
      'receive_sms_notifications': 'Receive notifications by SMS',
      'push_enabled': 'Push notifications enabled',
      'push_disabled': 'Push notifications disabled',
      'email_enabled': 'Email notifications enabled',
      'email_disabled': 'Email notifications disabled',
      'sms_enabled': 'SMS notifications enabled',
      'sms_disabled': 'SMS notifications disabled',
      'modify_current_password': 'Modify your current password',
      'logout_from_app': 'Log out from the application',
      'other_sessions_disconnected': 'Other sessions disconnected',
      'current_session': 'Current session',
      'today_at': 'Today at',
      'daily_at': 'Daily at',
      'backup_started': 'Backup started',
      'backup_download': 'Downloading backup...',
      'pdf_export_progress': 'PDF export in progress...',
      'excel_export_progress': 'Excel export in progress...',
      'json_export_progress': 'JSON export in progress...',
      'cache_cleared_mb': 'Cache cleared successfully',
      'reset_warning': 'Are you sure you want to reset all settings?',
      'settings_reset': 'Settings reset',
      'profile_updated': 'Profile updated',
      'total': 'Total',
      'in_progress': 'In progress',
      
      // Main Layout
      'profile_admin': 'Administrator Profile',
      'member_since': 'Member since',
      'january': 'January',
      'role': 'Role',
      'average': 'Average',
      'appointment_added': 'Appointment created successfully',
      'appointment_updated': 'Appointment updated successfully',
      'appointment_deleted': 'Appointment deleted successfully',
      
      // Finances
      'consultations': 'Consultations',
      'surgeries': 'Surgeries',
      'analyses': 'Analyses',
      'others': 'Others',
      'salaries': 'Salaries',
      'supplies': 'Supplies',
      'maintenance': 'Maintenance',
      'energy': 'Energy',
      'budget_total': 'Total Budget',
      'used': 'Used',
      'usage_rate': 'Usage rate',
      'cardiology': 'Cardiology',
      'pediatrics': 'Pediatrics',
      'emergencies': 'Emergencies',
      'jan': 'Jan',
      'feb': 'Feb',
      'mar': 'Mar',
      'apr': 'Apr',
      'may': 'May',
      'jun': 'Jun',
      
      // Reports
      'patients_treated': 'Patients treated',
      'occupation_rate': 'Occupation rate',
      'executive_summary': 'Executive Summary',
      'main_statistics': 'Main Statistics',
      
      // Care types
      'consultation_cardiology': 'Cardiology consultation',
      'medical_supplies': 'Medical supplies',
    },
    
    // ==================== ARABE ====================
    'العربية': {
      // Application / Header
      'hospital_name': 'المستشفى المركزي',
      'admin_panel': 'الإدارة',
      
      // Login
      'login': 'تسجيل الدخول',
      'welcome_back': 'مرحباً بعودتك',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'login_button': 'دخول',
      'please_enter_email': 'الرجاء إدخال البريد الإلكتروني',
      'please_enter_password': 'الرجاء إدخال كلمة المرور',
      'invalid_credentials': 'بيانات الدخول غير صحيحة',
      
      // Navigation
      'dashboard': 'لوحة القيادة',
      'patients': 'المرضى',
      'appointments': 'المواعيد',
      'services': 'الخدمات',
      'care': 'الرعاية',
      'finance': 'المالية',
      'reports': 'التقارير',
      'notifications': 'الإشعارات',
      'settings': 'الإعدادات',
      'logout': 'تسجيل الخروج',
      
      // Dashboard
      'good_morning': 'صباح الخير',
      'good_afternoon': 'مساء الخير',
      'good_evening': 'مساء الخير',
      'total_patients': 'إجمالي المرضى',
      'appointments_today': 'مواعيد اليوم',
      'available_beds': 'الأسرة المتاحة',
      'monthly_revenue': 'إيرادات الشهر',
      'recent_activity': 'النشاط الأخير',
      'quick_stats': 'إحصائيات سريعة',
      'budget_by_service': 'الميزانية حسب الخدمة',
      'recent_care': 'الرعاية الأخيرة',
      'quick_actions': 'إجراءات سريعة',
      'new_patient': 'مريض جديد',
      'budget': 'الميزانية',
      'current_cost': 'التكلفة الحالية',
      'no_service': 'لا توجد خدمة',
      'no_recent_care': 'لا توجد رعاية حديثة',
      'active': 'نشط',
      'inactive': 'غير نشط',
      
      // Patients
      'patient_list': 'قائمة المرضى',
      'add_patient': 'إضافة مريض',
      'edit_patient': 'تعديل مريض',
      'delete_patient': 'حذف مريض',
      'search_patient': 'البحث عن مريض...',
      'name': 'الاسم',
      'first_name': 'الاسم الأول',
      'birth_date': 'تاريخ الميلاد',
      'phone': 'الهاتف',
      'address': 'العنوان',
      'gender': 'الجنس',
      'male': 'ذكر',
      'female': 'أنثى',
      'blood_type': 'فصيلة الدم',
      'social_security': 'رقم الضمان الاجتماعي',
      'no_patient_found': 'لم يتم العثور على مريض',
      'patient_added': 'تمت إضافة المريض بنجاح',
      'patient_updated': 'تم تعديل المريض بنجاح',
      'patient_deleted': 'تم حذف المريض بنجاح',
      'patient_details': 'تفاصيل المريض',
      'select_date': 'اختر تاريخ',
      'total_cost': 'التكلفة الإجمالية',
      'care_count': 'عدد الرعاية',
      
      // Services
      'service_list': 'قائمة الخدمات',
      'add_service': 'إضافة خدمة',
      'edit_service': 'تعديل خدمة',
      'delete_service': 'حذف خدمة',
      'search_service': 'البحث عن خدمة...',
      'service_name': 'اسم الخدمة',
      'description': 'الوصف',
      'monthly_budget': 'الميزانية الشهرية',
      'annual_budget': 'الميزانية السنوية',
      'no_service_found': 'لم يتم العثور على خدمة',
      'service_added': 'تمت إضافة الخدمة بنجاح',
      'service_updated': 'تم تعديل الخدمة بنجاح',
      'service_deleted': 'تم حذف الخدمة بنجاح',
      
      // Soins/Care
      'care_list': 'قائمة الرعاية',
      'add_care': 'إضافة رعاية',
      'edit_care': 'تعديل رعاية',
      'delete_care': 'حذف رعاية',
      'search_care': 'البحث عن رعاية...',
      'care_type': 'نوع الرعاية',
      'care_date': 'تاريخ الرعاية',
      'care_cost': 'تكلفة الرعاية',
      'notes': 'ملاحظات',
      'select_patient': 'اختر مريض',
      'select_service': 'اختر خدمة',
      'no_care_found': 'لم يتم العثور على رعاية',
      'care_added': 'تمت إضافة الرعاية بنجاح',
      'care_updated': 'تم تعديل الرعاية بنجاح',
      'care_deleted': 'تم حذف الرعاية بنجاح',
      
      // Appointments
      'appointment_list': 'قائمة المواعيد',
      'add_appointment': 'موعد جديد',
      'edit_appointment': 'تعديل الموعد',
      'delete_appointment': 'حذف الموعد',
      'search_appointment': 'البحث عن موعد...',
      'date': 'التاريخ',
      'time': 'الوقت',
      'doctor': 'الطبيب',
      'reason': 'السبب',
      'status': 'الحالة',
      'pending': 'قيد الانتظار',
      'confirmed': 'مؤكد',
      'cancelled': 'ملغى',
      'completed': 'مكتمل',
      'no_appointment_found': 'لم يتم العثور على موعد',
      
      // Finance
      'finance_overview': 'الإدارة المالية للمؤسسة',
      'total_revenue': 'إجمالي الإيرادات',
      'total_expenses': 'إجمالي المصروفات',
      'net_profit': 'صافي الربح',
      'pending_invoices': 'الفواتير المعلقة',
      'export': 'تصدير',
      'export_pdf': 'تصدير PDF',
      'export_excel': 'تصدير Excel',
      'export_csv': 'تصدير CSV',
      'revenue_vs_expenses': 'الإيرادات مقابل المصروفات',
      'recent_transactions': 'المعاملات الأخيرة',
      'overview': 'نظرة عامة',
      'revenue': 'الإيرادات',
      'expenses': 'المصروفات',
      'week': 'أسبوع',
      'month': 'شهر',
      'year': 'سنة',
      'export_success': 'تم تحميل التصدير بنجاح',
      'export_error': 'خطأ في التصدير',
      'revenue_sources': 'مصادر الإيرادات',
      'top_services': 'أفضل الخدمات',
      'consultations': 'الاستشارات',
      'surgeries': 'الجراحات',
      'analyses': 'التحاليل',
      'other': 'أخرى',
      'revenue_details': 'تفاصيل الإيرادات',
      'date': 'التاريخ',
      'description': 'الوصف',
      'service': 'الخدمة',
      'amount': 'المبلغ',
      'category': 'الفئة',
      'expenses_by_category': 'المصروفات حسب الفئة',
      'expenses_trend': 'اتجاه المصروفات',
      'recent_expenses': 'المصروفات الأخيرة',
      'salaries': 'الرواتب',
      'supplies': 'المستلزمات',
      'maintenance': 'الصيانة',
      'energy': 'الطاقة',
      'total_budget': 'الميزانية الإجمالية',
      'used': 'المستخدم',
      'remaining': 'المتبقي',
      'usage_rate': 'معدل الاستخدام',
      'budget_by_service': 'الميزانية حسب الخدمة',
      'export_finances': 'تصدير الماليات',
      'complete_report_with_charts': 'تقرير كامل مع الرسوم البيانية',
      'detailed_data_table': 'بيانات مفصلة في جدول',
      'compatible_format': 'تنسيق متوافق مع جميع الأدوات',
      'cancel': 'إلغاء',
      'export_downloaded_success': 'تم تحميل {format} بنجاح!',
      'export_error_format': 'خطأ في تصدير {format}',
      'december_salaries': 'رواتب ديسمبر',
      'medical_consumables': 'المستهلكات الطبية',
      'scanner_repair': 'إصلاح الماسح الضوئي',
      'electricity_bill': 'فاتورة الكهرباء',
      'cardiology_consultation': 'استشارة قلب',
      'medical_supplies': 'المستلزمات الطبية',
      'lab_analysis': 'تحليل مختبري',
      'equipment_maintenance': 'صيانة المعدات',
      'outpatient_surgery': 'جراحة خارجية',
      'month_jan': 'يناير',
      'month_feb': 'فبراير',
      'month_mar': 'مارس',
      'month_apr': 'أبريل',
      'month_may': 'مايو',
      'month_jun': 'يونيو',
      
      // Reports
      'reports_title': 'إحصائيات وتحليلات المستشفى',
      'generate_report': 'إنشاء تقرير',
      'monthly_report': 'التقرير الشهري',
      'download': 'تحميل',
      'view': 'عرض',
      'print': 'طباعة',
      'print_report': 'طباعة التقرير',
      'print_directly': 'طباعة التقرير مباشرة',
      'report_type': 'نوع التقرير',
      'all': 'الكل',
      'monthly_evolution': 'التطور الشهري',
      'distribution_by_service': 'التوزيع حسب الخدمة',
      'recent_reports': 'التقارير الأخيرة',
      'see_all': 'عرض الكل',
      'export_reports': 'تصدير التقارير',
      'patients_treated': 'المرضى المعالجين',
      'revenue_label': 'الإيرادات',
      'consultations_label': 'الاستشارات',
      'occupation_rate': 'معدل الإشغال',
      'patients_chart': 'المرضى',
      'revenue_chart': 'الإيرادات (ك€)',
      'cardiology': 'أمراض القلب',
      'pediatrics': 'طب الأطفال',
      'emergency': 'الطوارئ',
      'monthly_report_june': 'التقرير الشهري - يونيو 2024',
      'financial_analysis_q2': 'التحليل المالي - الربع الثاني',
      'patient_statistics': 'إحصائيات المرضى',
      'service_performance': 'أداء الخدمات',
      'general': 'عام',
      'finances': 'الماليات',
      'report_downloaded': 'تم تحميل "{title}"!',
      'report_download_error': 'خطأ في تحميل "{title}"',
      'executive_summary': 'ملخص تنفيذي',
      'executive_summary_text': 'يقدم هذا التقرير تحليلاً شاملاً لأنشطة المستشفى للفترة المحددة. تظهر المؤشرات الرئيسية تحسناً بنسبة 12% في الأداء العام.',
      'main_statistics': 'الإحصائيات الرئيسية',
      'main_statistics_text': '• عدد المرضى المعالجين: 1,234\n• معدل الإشغال: 78%\n• متوسط مدة الإقامة: 4.2 أيام\n• معدل الرضا: 92%',
      'financial_performance': 'الأداء المالي',
      'financial_performance_text': '• إجمالي الإيرادات: 56,780 €\n• التكاليف التشغيلية: 42,300 €\n• هامش الربح: 25.5%\n• النمو مقابل الفترة السابقة: +8%',
      'recommendations': 'التوصيات',
      'recommendations_text': '1. تحسين معدل إشغال الأسرة\n2. تقليل أوقات الانتظار في الطوارئ\n3. تحسين المتابعة بعد الاستشارة\n4. الاستثمار في معدات التشخيص',
      'close': 'إغلاق',
      
      // Notifications
      'notification_list': 'قائمة الإشعارات',
      'mark_all_read': 'تحديد الكل كمقروء',
      'no_notifications': 'لا توجد إشعارات',
      'today': 'اليوم',
      'yesterday': 'أمس',
      'this_week': 'هذا الأسبوع',
      
      // Settings
      'settings_title': 'تكوين التطبيق الخاص بك',
      'profile': 'الملف الشخصي',
      'preferences': 'التفضيلات',
      'account': 'الحساب',
      'appearance': 'المظهر',
      'change_password': 'تغيير كلمة المرور',
      'current_password': 'كلمة المرور الحالية',
      'new_password': 'كلمة المرور الجديدة',
      'confirm_password': 'تأكيد كلمة المرور',
      'language': 'اللغة',
      'choose_language': 'اختر لغة التطبيق',
      'dark_mode': 'الوضع الداكن',
      'enable_dark_theme': 'تفعيل المظهر الداكن',
      'notifications_enabled': 'الإشعارات مفعلة',
      'push_notifications': 'إشعارات فورية',
      'email_notifications': 'إشعارات البريد',
      'sms_notifications': 'إشعارات SMS',
      'date_format': 'تنسيق التاريخ',
      'choose_date_format': 'اختر تنسيق العرض',
      'security': 'الأمان',
      'two_factor': 'التحقق بخطوتين',
      'active_sessions': 'الجلسات النشطة',
      'manage_sessions': 'إدارة الجلسات المتصلة',
      'data': 'البيانات',
      'export_data': 'تصدير البيانات',
      'download_data_copy': 'تحميل نسخة من بياناتك',
      'backups': 'النسخ الاحتياطي',
      'manage_backups': 'إدارة النسخ الاحتياطي التلقائي',
      'clear_cache': 'مسح ذاكرة التخزين',
      'free_storage': 'تحرير مساحة التخزين',
      'danger_zone': 'منطقة الخطر',
      'reset_settings': 'إعادة تعيين الإعدادات',
      'restore_defaults': 'استعادة الإعدادات الافتراضية',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'close': 'إغلاق',
      
      // Common/Messages
      'actions': 'الإجراءات',
      'edit': 'تعديل',
      'delete': 'حذف',
      'confirm': 'تأكيد',
      'success': 'نجاح',
      'error': 'خطأ',
      'loading': 'جاري التحميل...',
      'no_data': 'لا توجد بيانات',
      'search': 'بحث',
      'filter': 'تصفية',
      'yes': 'نعم',
      'no': 'لا',
      'back': 'رجوع',
      'next': 'التالي',
      'previous': 'السابق',
      'required_field': 'هذا الحقل مطلوب',
      'confirm_delete': 'هل أنت متأكد من الحذف؟',
      'delete_success': 'تم الحذف بنجاح',
      'save_success': 'تم الحفظ بنجاح',
      'password_changed': 'تم تغيير كلمة المرور بنجاح',
      'password_error': 'كلمة المرور الحالية غير صحيحة',
      'password_mismatch': 'كلمات المرور غير متطابقة',
      'password_too_short': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
      'passwords_dont_match': 'كلمات المرور غير متطابقة',
      'language_changed': 'تم تغيير اللغة بنجاح',
      'changes_saved': 'تم حفظ التغييرات',
      'operation_success': 'تمت العملية بنجاح',
      'operation_failed': 'فشلت العملية',
      
      // إعداد كلمة المرور الأولي
      'initial_password_setup': 'إعداد كلمة المرور الأولية',
      'setup_password_description': 'يرجى تعيين كلمة المرور لتأمين حسابك',
      'password_min_length': '6 أحرف كحد أدنى',
      'password_setup_success': 'تم تعيين كلمة المرور بنجاح. يمكنك الآن تسجيل الدخول.',
      'password_setup_error': 'خطأ في إعداد كلمة المرور',
      'setup_password_button': 'تعيين كلمة المرور',
      
      // مفاتيح إضافية للحوارات والنماذج
      'create': 'إنشاء',
      'modify': 'تعديل',
      'new_service': 'خدمة جديدة',
      'modify_service': 'تعديل الخدمة',
      'new_care': 'رعاية جديدة',
      'modify_care': 'تعديل الرعاية',
      'new_appointment': 'موعد جديد',
      'modify_appointment': 'تعديل الموعد',
      'new_patient_title': 'مريض جديد',
      'modify_patient': 'تعديل المريض',
      'patient_id': 'رقم المريض',
      'cost_euro': 'التكلفة (€)',
      'budget_euro': 'الميزانية (€)',
      'budget_used': 'الميزانية المستخدمة',
      'remaining': 'المتبقي',
      'fill_required_fields': 'يرجى ملء جميع الحقول المطلوبة',
      'confirm_delete_service': 'هل تريد حقاً حذف هذه الخدمة؟',
      'confirm_delete_care': 'هل تريد حقاً حذف هذه الرعاية؟',
      'confirm_delete_appointment': 'هل تريد حقاً حذف هذا الموعد؟',
      'confirm_delete_patient': 'هل تريد حقاً حذف هذا المريض؟',
      'retry': 'إعادة المحاولة',
      'total_cost': 'التكلفة الإجمالية',
      'statistics': 'الإحصائيات',
      'appointments_for_date': 'مواعيد اليوم',
      'no_appointments_for_date': 'لا توجد مواعيد لهذا التاريخ',
      'status_updated': 'تم تحديث الحالة',
      'notes_optional': 'ملاحظات (اختياري)',
      'patient_details': 'تفاصيل المريض',
      'no_care_recorded': 'لا توجد رعاية مسجلة',
      'select_date': 'اختر تاريخ',
      'please_select_date': 'يرجى اختيار تاريخ',
      
      // أنواع الرعاية
      'consultation': 'استشارة',
      'surgery': 'جراحة',
      'analysis': 'تحليل',
      'radiology': 'أشعة',
      'emergency': 'طوارئ',
      
      // إعدادات إضافية
      'modify_profile': 'تعديل الملف الشخصي',
      'administrator': 'المدير',
      'super_admin': 'المدير العام',
      'enable_2fa': 'تفعيل 2FA',
      'disable_2fa': 'إلغاء 2FA',
      'scan_qr_code': 'امسح رمز QR هذا',
      'enter_2fa_code': 'أدخل رمز 2FA الخاص بك',
      'verification_code': 'رمز التحقق',
      'invalid_code': 'رمز غير صالح (6 أرقام على الأقل)',
      '2fa_enabled': 'تم تفعيل 2FA بنجاح',
      '2fa_disabled': 'تم إلغاء 2FA',
      'current': 'الحالي',
      'disconnect_all': 'قطع الاتصال بالكل',
      'last_backup': 'آخر نسخة احتياطية',
      'auto_backup': 'نسخ احتياطي تلقائي',
      'backup_now': 'نسخ احتياطي الآن',
      'json_export': 'تصدير JSON',
      'clear_cache_confirm': 'سيؤدي هذا إلى حذف الملفات المؤقتة. متابعة؟',
      'cache_cleared': 'تم مسح ذاكرة التخزين بنجاح',
      'reset_confirm': 'هل أنت متأكد من إعادة تعيين جميع الإعدادات؟',
      'logout_confirm': 'هل أنت متأكد من تسجيل الخروج؟',
      'report_complete': 'تقرير كامل مع الرسوم البيانية',
      'detailed_data': 'بيانات مفصلة في جدول',
      'compatible_format': 'تنسيق متوافق مع جميع الأدوات',
      'print_directly': 'طباعة التقرير مباشرة',
      'view_all': 'عرض الكل',
      'export_reports': 'تصدير التقارير',
      'export_finances': 'تصدير المالية',
      'income_sources': 'مصادر الدخل',
      'top_services': 'أفضل الخدمات',
      'revenue_details': 'تفاصيل الإيرادات',
      'expense_categories': 'فئات المصروفات',
      'expense_trend': 'اتجاه المصروفات',
      'recent_expenses': 'المصروفات الأخيرة',
      'category': 'الفئة',
      'amount': 'المبلغ',
      
      // الإشعارات
      'unread': 'غير مقروءة',
      'info': 'معلومات',
      'warning': 'تحذير',
      'mark_read': 'تحديد كمقروء',
      'mark_unread': 'تحديد كغير مقروء',
      'summary': 'الملخص',
      'errors': 'الأخطاء',
      'all_read': 'تم تحديد جميع الإشعارات كمقروءة',
      'notification_deleted': 'تم حذف الإشعار',
      
      // إعدادات - مفاتيح إضافية
      'receive_push_notifications': 'استقبال الإشعارات في التطبيق',
      'receive_email_notifications': 'استقبال الإشعارات عبر البريد الإلكتروني',
      'receive_sms_notifications': 'استقبال الإشعارات عبر الرسائل القصيرة',
      'push_enabled': 'تم تفعيل إشعارات الدفع',
      'push_disabled': 'تم إلغاء إشعارات الدفع',
      'email_enabled': 'تم تفعيل إشعارات البريد الإلكتروني',
      'email_disabled': 'تم إلغاء إشعارات البريد الإلكتروني',
      'sms_enabled': 'تم تفعيل إشعارات الرسائل القصيرة',
      'sms_disabled': 'تم إلغاء إشعارات الرسائل القصيرة',
      'modify_current_password': 'تعديل كلمة المرور الحالية',
      'logout_from_app': 'تسجيل الخروج من التطبيق',
      'other_sessions_disconnected': 'تم قطع الاتصال بالجلسات الأخرى',
      'current_session': 'الجلسة الحالية',
      'today_at': 'اليوم في',
      'daily_at': 'يومياً في',
      'backup_started': 'بدأت النسخة الاحتياطية',
      'backup_download': 'جاري تحميل النسخة الاحتياطية...',
      'pdf_export_progress': 'جاري تصدير PDF...',
      'excel_export_progress': 'جاري تصدير Excel...',
      'json_export_progress': 'جاري تصدير JSON...',
      'cache_cleared_mb': 'تم مسح ذاكرة التخزين بنجاح',
      'reset_warning': 'هل أنت متأكد من إعادة تعيين جميع الإعدادات؟',
      'settings_reset': 'تم إعادة تعيين الإعدادات',
      'profile_updated': 'تم تحديث الملف الشخصي',
      'total': 'المجموع',
      'in_progress': 'قيد التنفيذ',
      
      // التخطيط الرئيسي
      'profile_admin': 'ملف المدير',
      'member_since': 'عضو منذ',
      'january': 'يناير',
      'role': 'الدور',
      'average': 'المتوسط',
      'appointment_added': 'تم إنشاء الموعد بنجاح',
      'appointment_updated': 'تم تعديل الموعد بنجاح',
      'appointment_deleted': 'تم حذف الموعد بنجاح',
      
      // المالية
      'consultations': 'الاستشارات',
      'surgeries': 'العمليات الجراحية',
      'analyses': 'التحاليل',
      'others': 'أخرى',
      'salaries': 'الرواتب',
      'supplies': 'اللوازم',
      'maintenance': 'الصيانة',
      'energy': 'الطاقة',
      'budget_total': 'إجمالي الميزانية',
      'used': 'مستخدم',
      'usage_rate': 'معدل الاستخدام',
      'cardiology': 'القلب',
      'pediatrics': 'الأطفال',
      'emergencies': 'الطوارئ',
      'jan': 'يناير',
      'feb': 'فبراير',
      'mar': 'مارس',
      'apr': 'أبريل',
      'may': 'مايو',
      'jun': 'يونيو',
      
      // التقارير
      'patients_treated': 'المرضى المعالجون',
      'occupation_rate': 'معدل الإشغال',
      'executive_summary': 'الملخص التنفيذي',
      'main_statistics': 'الإحصائيات الرئيسية',
      
      // أنواع الرعاية
      'consultation_cardiology': 'استشارة قلب',
      'medical_supplies': 'مستلزمات طبية',
    },
  };
}

/// Extension pour faciliter l'utilisation dans les widgets
extension LocalizationExtension on WidgetRef {
  /// Obtenir une traduction par clé
  String tr(String key) {
    final language = watch(languageProvider);
    return AppLocalizations.get(key, language);
  }
  
  /// Vérifie si la langue actuelle est RTL (arabe)
  bool get isRTL {
    final language = watch(languageProvider);
    return language == 'العربية';
  }
  
  /// Obtenir la direction du texte actuelle
  TextDirection get textDirection {
    return isRTL ? TextDirection.rtl : TextDirection.ltr;
  }
}
